#ifndef SYSNUMS_64_H
#define SYSNUMS_64_H

// AUTO-GENERATED, DO NOT MODIFY


#define	SYS_read		0	//read
#define	SYS_write		1	//write
#define	SYS_open		2	//open
#define	SYS_close		3	//close
#define	SYS_stat		4	//stat
#define	SYS_fstat		5	//fstat
#define	SYS_lstat		6	//lstat
#define	SYS_poll		7	//poll
#define	SYS_lseek		8	//lseek
#define	SYS_mmap		9	//mmap
#define	SYS_mprotect		10	//mprotect
#define	SYS_munmap		11	//munmap
#define	SYS_brk		12	//brk
#define	SYS_rt_sigaction		13	//rt_sigaction
#define	SYS_rt_sigprocmask		14	//rt_sigprocmask
#define	SYS_rt_sigreturn		15	//rt_sigreturn
#define	SYS_ioctl		16	//ioctl
#define	SYS_pread64		17	//pread64
#define	SYS_pwrite64		18	//pwrite64
#define	SYS_readv		19	//readv
#define	SYS_writev		20	//writev
#define	SYS_access		21	//access
#define	SYS_pipe		22	//pipe
#define	SYS_select		23	//select
#define	SYS_sched_yield		24	//sched_yield
#define	SYS_mremap		25	//mremap
#define	SYS_msync		26	//msync
#define	SYS_mincore		27	//mincore
#define	SYS_madvise		28	//madvise
#define	SYS_shmget		29	//shmget
#define	SYS_shmat		30	//shmat
#define	SYS_shmctl		31	//shmctl
#define	SYS_dup		32	//dup
#define	SYS_dup2		33	//dup2
#define	SYS_pause		34	//pause
#define	SYS_nanosleep		35	//nanosleep
#define	SYS_getitimer		36	//getitimer
#define	SYS_alarm		37	//alarm
#define	SYS_setitimer		38	//setitimer
#define	SYS_getpid		39	//getpid
#define	SYS_sendfile		40	//sendfile
#define	SYS_socket		41	//socket
#define	SYS_connect		42	//connect
#define	SYS_accept		43	//accept
#define	SYS_sendto		44	//sendto
#define	SYS_recvfrom		45	//recvfrom
#define	SYS_sendmsg		46	//sendmsg
#define	SYS_recvmsg		47	//recvmsg
#define	SYS_shutdown		48	//shutdown
#define	SYS_bind		49	//bind
#define	SYS_listen		50	//listen
#define	SYS_getsockname		51	//getsockname
#define	SYS_getpeername		52	//getpeername
#define	SYS_socketpair		53	//socketpair
#define	SYS_setsockopt		54	//setsockopt
#define	SYS_getsockopt		55	//getsockopt
#define	SYS_clone		56	//clone
#define	SYS_fork		57	//fork
#define	SYS_vfork		58	//vfork
#define	SYS_execve		59	//execve
#define	SYS_exit		60	//exit
#define	SYS_wait4		61	//wait4
#define	SYS_kill		62	//kill
#define	SYS_uname		63	//uname
#define	SYS_semget		64	//semget
#define	SYS_semop		65	//semop
#define	SYS_semctl		66	//semctl
#define	SYS_shmdt		67	//shmdt
#define	SYS_msgget		68	//msgget
#define	SYS_msgsnd		69	//msgsnd
#define	SYS_msgrcv		70	//msgrcv
#define	SYS_msgctl		71	//msgctl
#define	SYS_fcntl		72	//fcntl
#define	SYS_flock		73	//flock
#define	SYS_fsync		74	//fsync
#define	SYS_fdatasync		75	//fdatasync
#define	SYS_truncate		76	//truncate
#define	SYS_ftruncate		77	//ftruncate
#define	SYS_getdents		78	//getdents
#define	SYS_getcwd		79	//getcwd
#define	SYS_chdir		80	//chdir
#define	SYS_fchdir		81	//fchdir
#define	SYS_rename		82	//rename
#define	SYS_mkdir		83	//mkdir
#define	SYS_rmdir		84	//rmdir
#define	SYS_creat		85	//creat
#define	SYS_link		86	//link
#define	SYS_unlink		87	//unlink
#define	SYS_symlink		88	//symlink
#define	SYS_readlink		89	//readlink
#define	SYS_chmod		90	//chmod
#define	SYS_fchmod		91	//fchmod
#define	SYS_chown		92	//chown
#define	SYS_fchown		93	//fchown
#define	SYS_lchown		94	//lchown
#define	SYS_umask		95	//umask
#define	SYS_gettimeofday		96	//gettimeofday
#define	SYS_getrlimit		97	//getrlimit
#define	SYS_getrusage		98	//getrusage
#define	SYS_sysinfo		99	//sysinfo
#define	SYS_times		100	//times
#define	SYS_ptrace		101	//ptrace
#define	SYS_getuid		102	//getuid
#define	SYS_syslog		103	//syslog
#define	SYS_getgid		104	//getgid
#define	SYS_setuid		105	//setuid
#define	SYS_setgid		106	//setgid
#define	SYS_geteuid		107	//geteuid
#define	SYS_getegid		108	//getegid
#define	SYS_setpgid		109	//setpgid
#define	SYS_getppid		110	//getppid
#define	SYS_getpgrp		111	//getpgrp
#define	SYS_setsid		112	//setsid
#define	SYS_setreuid		113	//setreuid
#define	SYS_setregid		114	//setregid
#define	SYS_getgroups		115	//getgroups
#define	SYS_setgroups		116	//setgroups
#define	SYS_setresuid		117	//setresuid
#define	SYS_getresuid		118	//getresuid
#define	SYS_setresgid		119	//setresgid
#define	SYS_getresgid		120	//getresgid
#define	SYS_getpgid		121	//getpgid
#define	SYS_setfsuid		122	//setfsuid
#define	SYS_setfsgid		123	//setfsgid
#define	SYS_getsid		124	//getsid
#define	SYS_capget		125	//capget
#define	SYS_capset		126	//capset
#define	SYS_rt_sigpending		127	//rt_sigpending
#define	SYS_rt_sigtimedwait		128	//rt_sigtimedwait
#define	SYS_rt_sigqueueinfo		129	//rt_sigqueueinfo
#define	SYS_rt_sigsuspend		130	//rt_sigsuspend
#define	SYS_sigaltstack		131	//sigaltstack
#define	SYS_utime		132	//utime
#define	SYS_mknod		133	//mknod
#define	SYS_uselib		134	//uselib
#define	SYS_personality		135	//personality
#define	SYS_ustat		136	//ustat
#define	SYS_statfs		137	//statfs
#define	SYS_fstatfs		138	//fstatfs
#define	SYS_sysfs		139	//sysfs
#define	SYS_getpriority		140	//getpriority
#define	SYS_setpriority		141	//setpriority
#define	SYS_sched_setparam		142	//sched_setparam
#define	SYS_sched_getparam		143	//sched_getparam
#define	SYS_sched_setscheduler		144	//sched_setscheduler
#define	SYS_sched_getscheduler		145	//sched_getscheduler
#define	SYS_sched_get_priority_max		146	//sched_get_priority_max
#define	SYS_sched_get_priority_min		147	//sched_get_priority_min
#define	SYS_sched_rr_get_interval		148	//sched_rr_get_interval
#define	SYS_mlock		149	//mlock
#define	SYS_munlock		150	//munlock
#define	SYS_mlockall		151	//mlockall
#define	SYS_munlockall		152	//munlockall
#define	SYS_vhangup		153	//vhangup
#define	SYS_modify_ldt		154	//modify_ldt
#define	SYS_pivot_root		155	//pivot_root
#define	SYS__sysctl		156	//_sysctl
#define	SYS_prctl		157	//prctl
#define	SYS_arch_prctl		158	//arch_prctl
#define	SYS_adjtimex		159	//adjtimex
#define	SYS_setrlimit		160	//setrlimit
#define	SYS_chroot		161	//chroot
#define	SYS_sync		162	//sync
#define	SYS_acct		163	//acct
#define	SYS_settimeofday		164	//settimeofday
#define	SYS_mount		165	//mount
#define	SYS_umount2		166	//umount2
#define	SYS_swapon		167	//swapon
#define	SYS_swapoff		168	//swapoff
#define	SYS_reboot		169	//reboot
#define	SYS_sethostname		170	//sethostname
#define	SYS_setdomainname		171	//setdomainname
#define	SYS_iopl		172	//iopl
#define	SYS_ioperm		173	//ioperm
#define	SYS_create_module		174	//create_module
#define	SYS_init_module		175	//init_module
#define	SYS_delete_module		176	//delete_module
#define	SYS_get_kernel_syms		177	//get_kernel_syms
#define	SYS_query_module		178	//query_module
#define	SYS_quotactl		179	//quotactl
#define	SYS_nfsservctl		180	//nfsservctl
#define	SYS_getpmsg		181	//getpmsg
#define	SYS_putpmsg		182	//putpmsg
#define	SYS_afs_syscall		183	//afs_syscall
#define	SYS_tuxcall		184	//tuxcall
#define	SYS_security		185	//security
#define	SYS_gettid		186	//gettid
#define	SYS_readahead		187	//readahead
#define	SYS_setxattr		188	//setxattr
#define	SYS_lsetxattr		189	//lsetxattr
#define	SYS_fsetxattr		190	//fsetxattr
#define	SYS_getxattr		191	//getxattr
#define	SYS_lgetxattr		192	//lgetxattr
#define	SYS_fgetxattr		193	//fgetxattr
#define	SYS_listxattr		194	//listxattr
#define	SYS_llistxattr		195	//llistxattr
#define	SYS_flistxattr		196	//flistxattr
#define	SYS_removexattr		197	//removexattr
#define	SYS_lremovexattr		198	//lremovexattr
#define	SYS_fremovexattr		199	//fremovexattr
#define	SYS_tkill		200	//tkill
#define	SYS_time		201	//time
#define	SYS_futex		202	//futex
#define	SYS_sched_setaffinity		203	//sched_setaffinity
#define	SYS_sched_getaffinity		204	//sched_getaffinity
#define	SYS_set_thread_area		205	//set_thread_area
#define	SYS_io_setup		206	//io_setup
#define	SYS_io_destroy		207	//io_destroy
#define	SYS_io_getevents		208	//io_getevents
#define	SYS_io_submit		209	//io_submit
#define	SYS_io_cancel		210	//io_cancel
#define	SYS_get_thread_area		211	//get_thread_area
#define	SYS_lookup_dcookie		212	//lookup_dcookie
#define	SYS_epoll_create		213	//epoll_create
#define	SYS_epoll_ctl_old		214	//epoll_ctl_old
#define	SYS_epoll_wait_old		215	//epoll_wait_old
#define	SYS_remap_file_pages		216	//remap_file_pages
#define	SYS_getdents64		217	//getdents64
#define	SYS_set_tid_address		218	//set_tid_address
#define	SYS_restart_syscall		219	//restart_syscall
#define	SYS_semtimedop		220	//semtimedop
#define	SYS_fadvise64		221	//fadvise64
#define	SYS_timer_create		222	//timer_create
#define	SYS_timer_settime		223	//timer_settime
#define	SYS_timer_gettime		224	//timer_gettime
#define	SYS_timer_getoverrun		225	//timer_getoverrun
#define	SYS_timer_delete		226	//timer_delete
#define	SYS_clock_settime		227	//clock_settime
#define	SYS_clock_gettime		228	//clock_gettime
#define	SYS_clock_getres		229	//clock_getres
#define	SYS_clock_nanosleep		230	//clock_nanosleep
#define	SYS_exit_group		231	//exit_group
#define	SYS_epoll_wait		232	//epoll_wait
#define	SYS_epoll_ctl		233	//epoll_ctl
#define	SYS_tgkill		234	//tgkill
#define	SYS_utimes		235	//utimes
#define	SYS_vserver		236	//vserver
#define	SYS_mbind		237	//mbind
#define	SYS_set_mempolicy		238	//set_mempolicy
#define	SYS_get_mempolicy		239	//get_mempolicy
#define	SYS_mq_open		240	//mq_open
#define	SYS_mq_unlink		241	//mq_unlink
#define	SYS_mq_timedsend		242	//mq_timedsend
#define	SYS_mq_timedreceive		243	//mq_timedreceive
#define	SYS_mq_notify		244	//mq_notify
#define	SYS_mq_getsetattr		245	//mq_getsetattr
#define	SYS_kexec_load		246	//kexec_load
#define	SYS_waitid		247	//waitid
#define	SYS_add_key		248	//add_key
#define	SYS_request_key		249	//request_key
#define	SYS_keyctl		250	//keyctl
#define	SYS_ioprio_set		251	//ioprio_set
#define	SYS_ioprio_get		252	//ioprio_get
#define	SYS_inotify_init		253	//inotify_init
#define	SYS_inotify_add_watch		254	//inotify_add_watch
#define	SYS_inotify_rm_watch		255	//inotify_rm_watch
#define	SYS_migrate_pages		256	//migrate_pages
#define	SYS_openat		257	//openat
#define	SYS_mkdirat		258	//mkdirat
#define	SYS_mknodat		259	//mknodat
#define	SYS_fchownat		260	//fchownat
#define	SYS_futimesat		261	//futimesat
#define	SYS_newfstatat		262	//newfstatat
#define	SYS_unlinkat		263	//unlinkat
#define	SYS_renameat		264	//renameat
#define	SYS_linkat		265	//linkat
#define	SYS_symlinkat		266	//symlinkat
#define	SYS_readlinkat		267	//readlinkat
#define	SYS_fchmodat		268	//fchmodat
#define	SYS_faccessat		269	//faccessat
#define	SYS_pselect6		270	//pselect6
#define	SYS_ppoll		271	//ppoll
#define	SYS_unshare		272	//unshare
#define	SYS_set_robust_list		273	//set_robust_list
#define	SYS_get_robust_list		274	//get_robust_list
#define	SYS_splice		275	//splice
#define	SYS_tee		276	//tee
#define	SYS_sync_file_range		277	//sync_file_range
#define	SYS_vmsplice		278	//vmsplice
#define	SYS_move_pages		279	//move_pages
#define	SYS_utimensat		280	//utimensat
#define	SYS_epoll_pwait		281	//epoll_pwait
#define	SYS_signalfd		282	//signalfd
#define	SYS_timerfd_create		283	//timerfd_create
#define	SYS_eventfd		284	//eventfd
#define	SYS_fallocate		285	//fallocate
#define	SYS_timerfd_settime		286	//timerfd_settime
#define	SYS_timerfd_gettime		287	//timerfd_gettime
#define	SYS_accept4		288	//accept4
#define	SYS_signalfd4		289	//signalfd4
#define	SYS_eventfd2		290	//eventfd2
#define	SYS_epoll_create1		291	//epoll_create1
#define	SYS_dup3		292	//dup3
#define	SYS_pipe2		293	//pipe2
#define	SYS_inotify_init1		294	//inotify_init1
#define	SYS_preadv		295	//preadv
#define	SYS_pwritev		296	//pwritev
#define	SYS_rt_tgsigqueueinfo		297	//rt_tgsigqueueinfo
#define	SYS_perf_event_open		298	//perf_event_open
#define	SYS_recvmmsg		299	//recvmmsg
#define	SYS_fanotify_init		300	//fanotify_init
#define	SYS_fanotify_mark		301	//fanotify_mark
#define	SYS_prlimit64		302	//prlimit64
#define	SYS_name_to_handle_at		303	//name_to_handle_at
#define	SYS_open_by_handle_at		304	//open_by_handle_at
#define	SYS_clock_adjtime		305	//clock_adjtime
#define	SYS_syncfs		306	//syncfs
#define	SYS_sendmmsg		307	//sendmmsg
#define	SYS_setns		308	//setns
#define	SYS_getcpu		309	//getcpu
#define	SYS_process_vm_readv		310	//process_vm_readv
#define	SYS_process_vm_writev		311	//process_vm_writev
#define	SYS_kcmp		312	//kcmp
#define	SYS_finit_module		313	//finit_module
#define	SYS_sched_setattr		314	//sched_setattr
#define	SYS_sched_getattr		315	//sched_getattr
#define	SYS_renameat2		316	//renameat2
#define	SYS_seccomp		317	//seccomp
#define	SYS_getrandom		318	//getrandom
#define	SYS_memfd_create		319	//memfd_create
#define	SYS_kexec_file_load		320	//kexec_file_load
#define	SYS_bpf		321	//bpf
#define	SYS_execveat		322	//execveat
#define	SYS_userfaultfd		323	//userfaultfd
#define	SYS_membarrier		324	//membarrier
#define	SYS_mlock2		325	//mlock2
#define	SYS_copy_file_range		326	//copy_file_range
#define	SYS_preadv2		327	//preadv2
#define	SYS_pwritev2		328	//pwritev2
#define	SYS_pkey_mprotect		329	//pkey_mprotect
#define	SYS_pkey_alloc		330	//pkey_alloc
#define	SYS_pkey_free		331	//pkey_free
#define	SYS_statx		332	//statx

#endif
