#ifndef __/SRC/INTERNALS/SYSNUMS_32_H
#define __/SRC/INTERNALS/SYSNUMS_32_H

// AUTO-GENERATED, DO NOT MODIFY


#define		SYS_restart_syscall		0		//restart_syscall
#define		SYS_exit		1		//exit
#define		SYS_fork		2		//fork
#define		SYS_read		3		//read
#define		SYS_write		4		//write
#define		SYS_open		5		//open
#define		SYS_close		6		//close
#define		SYS_waitpid		7		//waitpid
#define		SYS_creat		8		//creat
#define		SYS_link		9		//link
#define		SYS_unlink		10		//unlink
#define		SYS_execve		11		//execve
#define		SYS_chdir		12		//chdir
#define		SYS_time		13		//time
#define		SYS_mknod		14		//mknod
#define		SYS_chmod		15		//chmod
#define		SYS_lchown		16		//lchown
#define		SYS_break		17		//break
#define		SYS_oldstat		18		//oldstat
#define		SYS_lseek		19		//lseek
#define		SYS_getpid		20		//getpid
#define		SYS_mount		21		//mount
#define		SYS_umount		22		//umount
#define		SYS_setuid		23		//setuid
#define		SYS_getuid		24		//getuid
#define		SYS_stime		25		//stime
#define		SYS_ptrace		26		//ptrace
#define		SYS_alarm		27		//alarm
#define		SYS_oldfstat		28		//oldfstat
#define		SYS_pause		29		//pause
#define		SYS_utime		30		//utime
#define		SYS_stty		31		//stty
#define		SYS_gtty		32		//gtty
#define		SYS_access		33		//access
#define		SYS_nice		34		//nice
#define		SYS_ftime		35		//ftime
#define		SYS_sync		36		//sync
#define		SYS_kill		37		//kill
#define		SYS_rename		38		//rename
#define		SYS_mkdir		39		//mkdir
#define		SYS_rmdir		40		//rmdir
#define		SYS_dup		41		//dup
#define		SYS_pipe		42		//pipe
#define		SYS_times		43		//times
#define		SYS_prof		44		//prof
#define		SYS_brk		45		//brk
#define		SYS_setgid		46		//setgid
#define		SYS_getgid		47		//getgid
#define		SYS_signal		48		//signal
#define		SYS_geteuid		49		//geteuid
#define		SYS_getegid		50		//getegid
#define		SYS_acct		51		//acct
#define		SYS_umount2		52		//umount2
#define		SYS_lock		53		//lock
#define		SYS_ioctl		54		//ioctl
#define		SYS_fcntl		55		//fcntl
#define		SYS_mpx		56		//mpx
#define		SYS_setpgid		57		//setpgid
#define		SYS_ulimit		58		//ulimit
#define		SYS_oldolduname		59		//oldolduname
#define		SYS_umask		60		//umask
#define		SYS_chroot		61		//chroot
#define		SYS_ustat		62		//ustat
#define		SYS_dup2		63		//dup2
#define		SYS_getppid		64		//getppid
#define		SYS_getpgrp		65		//getpgrp
#define		SYS_setsid		66		//setsid
#define		SYS_sigaction		67		//sigaction
#define		SYS_sgetmask		68		//sgetmask
#define		SYS_ssetmask		69		//ssetmask
#define		SYS_setreuid		70		//setreuid
#define		SYS_setregid		71		//setregid
#define		SYS_sigsuspend		72		//sigsuspend
#define		SYS_sigpending		73		//sigpending
#define		SYS_sethostname		74		//sethostname
#define		SYS_setrlimit		75		//setrlimit
#define		SYS_getrlimit		76		//getrlimit
#define		SYS_getrusage		77		//getrusage
#define		SYS_gettimeofday		78		//gettimeofday
#define		SYS_settimeofday		79		//settimeofday
#define		SYS_getgroups		80		//getgroups
#define		SYS_setgroups		81		//setgroups
#define		SYS_select		82		//select
#define		SYS_symlink		83		//symlink
#define		SYS_oldlstat		84		//oldlstat
#define		SYS_readlink		85		//readlink
#define		SYS_uselib		86		//uselib
#define		SYS_swapon		87		//swapon
#define		SYS_reboot		88		//reboot
#define		SYS_readdir		89		//readdir
#define		SYS_mmap		90		//mmap
#define		SYS_munmap		91		//munmap
#define		SYS_truncate		92		//truncate
#define		SYS_ftruncate		93		//ftruncate
#define		SYS_fchmod		94		//fchmod
#define		SYS_fchown		95		//fchown
#define		SYS_getpriority		96		//getpriority
#define		SYS_setpriority		97		//setpriority
#define		SYS_profil		98		//profil
#define		SYS_statfs		99		//statfs
#define		SYS_fstatfs		100		//fstatfs
#define		SYS_ioperm		101		//ioperm
#define		SYS_socketcall		102		//socketcall
#define		SYS_syslog		103		//syslog
#define		SYS_setitimer		104		//setitimer
#define		SYS_getitimer		105		//getitimer
#define		SYS_stat		106		//stat
#define		SYS_lstat		107		//lstat
#define		SYS_fstat		108		//fstat
#define		SYS_olduname		109		//olduname
#define		SYS_iopl		110		//iopl
#define		SYS_vhangup		111		//vhangup
#define		SYS_idle		112		//idle
#define		SYS_vm86old		113		//vm86old
#define		SYS_wait4		114		//wait4
#define		SYS_swapoff		115		//swapoff
#define		SYS_sysinfo		116		//sysinfo
#define		SYS_ipc		117		//ipc
#define		SYS_fsync		118		//fsync
#define		SYS_sigreturn		119		//sigreturn
#define		SYS_clone		120		//clone
#define		SYS_setdomainname		121		//setdomainname
#define		SYS_uname		122		//uname
#define		SYS_modify_ldt		123		//modify_ldt
#define		SYS_adjtimex		124		//adjtimex
#define		SYS_mprotect		125		//mprotect
#define		SYS_sigprocmask		126		//sigprocmask
#define		SYS_create_module		127		//create_module
#define		SYS_init_module		128		//init_module
#define		SYS_delete_module		129		//delete_module
#define		SYS_get_kernel_syms		130		//get_kernel_syms
#define		SYS_quotactl		131		//quotactl
#define		SYS_getpgid		132		//getpgid
#define		SYS_fchdir		133		//fchdir
#define		SYS_bdflush		134		//bdflush
#define		SYS_sysfs		135		//sysfs
#define		SYS_personality		136		//personality
#define		SYS_afs_syscall		137		//afs_syscall
#define		SYS_setfsuid		138		//setfsuid
#define		SYS_setfsgid		139		//setfsgid
#define		SYS__llseek		140		//_llseek
#define		SYS_getdents		141		//getdents
#define		SYS__newselect		142		//_newselect
#define		SYS_flock		143		//flock
#define		SYS_msync		144		//msync
#define		SYS_readv		145		//readv
#define		SYS_writev		146		//writev
#define		SYS_getsid		147		//getsid
#define		SYS_fdatasync		148		//fdatasync
#define		SYS__sysctl		149		//_sysctl
#define		SYS_mlock		150		//mlock
#define		SYS_munlock		151		//munlock
#define		SYS_mlockall		152		//mlockall
#define		SYS_munlockall		153		//munlockall
#define		SYS_sched_setparam		154		//sched_setparam
#define		SYS_sched_getparam		155		//sched_getparam
#define		SYS_sched_setscheduler		156		//sched_setscheduler
#define		SYS_sched_getscheduler		157		//sched_getscheduler
#define		SYS_sched_yield		158		//sched_yield
#define		SYS_sched_get_priority_max		159		//sched_get_priority_max
#define		SYS_sched_get_priority_min		160		//sched_get_priority_min
#define		SYS_sched_rr_get_interval		161		//sched_rr_get_interval
#define		SYS_nanosleep		162		//nanosleep
#define		SYS_mremap		163		//mremap
#define		SYS_setresuid		164		//setresuid
#define		SYS_getresuid		165		//getresuid
#define		SYS_vm86		166		//vm86
#define		SYS_query_module		167		//query_module
#define		SYS_poll		168		//poll
#define		SYS_nfsservctl		169		//nfsservctl
#define		SYS_setresgid		170		//setresgid
#define		SYS_getresgid		171		//getresgid
#define		SYS_prctl		172		//prctl
#define		SYS_rt_sigreturn		173		//rt_sigreturn
#define		SYS_rt_sigaction		174		//rt_sigaction
#define		SYS_rt_sigprocmask		175		//rt_sigprocmask
#define		SYS_rt_sigpending		176		//rt_sigpending
#define		SYS_rt_sigtimedwait		177		//rt_sigtimedwait
#define		SYS_rt_sigqueueinfo		178		//rt_sigqueueinfo
#define		SYS_rt_sigsuspend		179		//rt_sigsuspend
#define		SYS_pread64		180		//pread64
#define		SYS_pwrite64		181		//pwrite64
#define		SYS_chown		182		//chown
#define		SYS_getcwd		183		//getcwd
#define		SYS_capget		184		//capget
#define		SYS_capset		185		//capset
#define		SYS_sigaltstack		186		//sigaltstack
#define		SYS_sendfile		187		//sendfile
#define		SYS_getpmsg		188		//getpmsg
#define		SYS_putpmsg		189		//putpmsg
#define		SYS_vfork		190		//vfork
#define		SYS_ugetrlimit		191		//ugetrlimit
#define		SYS_mmap2		192		//mmap2
#define		SYS_truncate64		193		//truncate64
#define		SYS_ftruncate64		194		//ftruncate64
#define		SYS_stat64		195		//stat64
#define		SYS_lstat64		196		//lstat64
#define		SYS_fstat64		197		//fstat64
#define		SYS_lchown32		198		//lchown32
#define		SYS_getuid32		199		//getuid32
#define		SYS_getgid32		200		//getgid32
#define		SYS_geteuid32		201		//geteuid32
#define		SYS_getegid32		202		//getegid32
#define		SYS_setreuid32		203		//setreuid32
#define		SYS_setregid32		204		//setregid32
#define		SYS_getgroups32		205		//getgroups32
#define		SYS_setgroups32		206		//setgroups32
#define		SYS_fchown32		207		//fchown32
#define		SYS_setresuid32		208		//setresuid32
#define		SYS_getresuid32		209		//getresuid32
#define		SYS_setresgid32		210		//setresgid32
#define		SYS_getresgid32		211		//getresgid32
#define		SYS_chown32		212		//chown32
#define		SYS_setuid32		213		//setuid32
#define		SYS_setgid32		214		//setgid32
#define		SYS_setfsuid32		215		//setfsuid32
#define		SYS_setfsgid32		216		//setfsgid32
#define		SYS_pivot_root		217		//pivot_root
#define		SYS_mincore		218		//mincore
#define		SYS_madvise		219		//madvise
#define		SYS_getdents64		220		//getdents64
#define		SYS_fcntl64		221		//fcntl64
#define		SYS_gettid		224		//gettid
#define		SYS_readahead		225		//readahead
#define		SYS_setxattr		226		//setxattr
#define		SYS_lsetxattr		227		//lsetxattr
#define		SYS_fsetxattr		228		//fsetxattr
#define		SYS_getxattr		229		//getxattr
#define		SYS_lgetxattr		230		//lgetxattr
#define		SYS_fgetxattr		231		//fgetxattr
#define		SYS_listxattr		232		//listxattr
#define		SYS_llistxattr		233		//llistxattr
#define		SYS_flistxattr		234		//flistxattr
#define		SYS_removexattr		235		//removexattr
#define		SYS_lremovexattr		236		//lremovexattr
#define		SYS_fremovexattr		237		//fremovexattr
#define		SYS_tkill		238		//tkill
#define		SYS_sendfile64		239		//sendfile64
#define		SYS_futex		240		//futex
#define		SYS_sched_setaffinity		241		//sched_setaffinity
#define		SYS_sched_getaffinity		242		//sched_getaffinity
#define		SYS_set_thread_area		243		//set_thread_area
#define		SYS_get_thread_area		244		//get_thread_area
#define		SYS_io_setup		245		//io_setup
#define		SYS_io_destroy		246		//io_destroy
#define		SYS_io_getevents		247		//io_getevents
#define		SYS_io_submit		248		//io_submit
#define		SYS_io_cancel		249		//io_cancel
#define		SYS_fadvise64		250		//fadvise64
#define		SYS_exit_group		252		//exit_group
#define		SYS_lookup_dcookie		253		//lookup_dcookie
#define		SYS_epoll_create		254		//epoll_create
#define		SYS_epoll_ctl		255		//epoll_ctl
#define		SYS_epoll_wait		256		//epoll_wait
#define		SYS_remap_file_pages		257		//remap_file_pages
#define		SYS_set_tid_address		258		//set_tid_address
#define		SYS_timer_create		259		//timer_create
#define		SYS_timer_settime		260		//timer_settime
#define		SYS_timer_gettime		261		//timer_gettime
#define		SYS_timer_getoverrun		262		//timer_getoverrun
#define		SYS_timer_delete		263		//timer_delete
#define		SYS_clock_settime		264		//clock_settime
#define		SYS_clock_gettime		265		//clock_gettime
#define		SYS_clock_getres		266		//clock_getres
#define		SYS_clock_nanosleep		267		//clock_nanosleep
#define		SYS_statfs64		268		//statfs64
#define		SYS_fstatfs64		269		//fstatfs64
#define		SYS_tgkill		270		//tgkill
#define		SYS_utimes		271		//utimes
#define		SYS_fadvise64_64		272		//fadvise64_64
#define		SYS_vserver		273		//vserver
#define		SYS_mbind		274		//mbind
#define		SYS_get_mempolicy		275		//get_mempolicy
#define		SYS_set_mempolicy		276		//set_mempolicy
#define		SYS_mq_open		277		//mq_open
#define		SYS_mq_unlink		278		//mq_unlink
#define		SYS_mq_timedsend		279		//mq_timedsend
#define		SYS_mq_timedreceive		280		//mq_timedreceive
#define		SYS_mq_notify		281		//mq_notify
#define		SYS_mq_getsetattr		282		//mq_getsetattr
#define		SYS_kexec_load		283		//kexec_load
#define		SYS_waitid		284		//waitid
#define		SYS_add_key		286		//add_key
#define		SYS_request_key		287		//request_key
#define		SYS_keyctl		288		//keyctl
#define		SYS_ioprio_set		289		//ioprio_set
#define		SYS_ioprio_get		290		//ioprio_get
#define		SYS_inotify_init		291		//inotify_init
#define		SYS_inotify_add_watch		292		//inotify_add_watch
#define		SYS_inotify_rm_watch		293		//inotify_rm_watch
#define		SYS_migrate_pages		294		//migrate_pages
#define		SYS_openat		295		//openat
#define		SYS_mkdirat		296		//mkdirat
#define		SYS_mknodat		297		//mknodat
#define		SYS_fchownat		298		//fchownat
#define		SYS_futimesat		299		//futimesat
#define		SYS_fstatat64		300		//fstatat64
#define		SYS_unlinkat		301		//unlinkat
#define		SYS_renameat		302		//renameat
#define		SYS_linkat		303		//linkat
#define		SYS_symlinkat		304		//symlinkat
#define		SYS_readlinkat		305		//readlinkat
#define		SYS_fchmodat		306		//fchmodat
#define		SYS_faccessat		307		//faccessat
#define		SYS_pselect6		308		//pselect6
#define		SYS_ppoll		309		//ppoll
#define		SYS_unshare		310		//unshare
#define		SYS_set_robust_list		311		//set_robust_list
#define		SYS_get_robust_list		312		//get_robust_list
#define		SYS_splice		313		//splice
#define		SYS_sync_file_range		314		//sync_file_range
#define		SYS_tee		315		//tee
#define		SYS_vmsplice		316		//vmsplice
#define		SYS_move_pages		317		//move_pages
#define		SYS_getcpu		318		//getcpu
#define		SYS_epoll_pwait		319		//epoll_pwait
#define		SYS_utimensat		320		//utimensat
#define		SYS_signalfd		321		//signalfd
#define		SYS_timerfd_create		322		//timerfd_create
#define		SYS_eventfd		323		//eventfd
#define		SYS_fallocate		324		//fallocate
#define		SYS_timerfd_settime		325		//timerfd_settime
#define		SYS_timerfd_gettime		326		//timerfd_gettime
#define		SYS_signalfd4		327		//signalfd4
#define		SYS_eventfd2		328		//eventfd2
#define		SYS_epoll_create1		329		//epoll_create1
#define		SYS_dup3		330		//dup3
#define		SYS_pipe2		331		//pipe2
#define		SYS_inotify_init1		332		//inotify_init1
#define		SYS_preadv		333		//preadv
#define		SYS_pwritev		334		//pwritev
#define		SYS_rt_tgsigqueueinfo		335		//rt_tgsigqueueinfo
#define		SYS_perf_event_open		336		//perf_event_open
#define		SYS_recvmmsg		337		//recvmmsg
#define		SYS_fanotify_init		338		//fanotify_init
#define		SYS_fanotify_mark		339		//fanotify_mark
#define		SYS_prlimit64		340		//prlimit64
#define		SYS_name_to_handle_at		341		//name_to_handle_at
#define		SYS_open_by_handle_at		342		//open_by_handle_at
#define		SYS_clock_adjtime		343		//clock_adjtime
#define		SYS_syncfs		344		//syncfs
#define		SYS_sendmmsg		345		//sendmmsg
#define		SYS_setns		346		//setns
#define		SYS_process_vm_readv		347		//process_vm_readv
#define		SYS_process_vm_writev		348		//process_vm_writev
#define		SYS_kcmp		349		//kcmp
#define		SYS_finit_module		350		//finit_module
#define		SYS_sched_setattr		351		//sched_setattr
#define		SYS_sched_getattr		352		//sched_getattr
#define		SYS_renameat2		353		//renameat2
#define		SYS_seccomp		354		//seccomp
#define		SYS_getrandom		355		//getrandom
#define		SYS_memfd_create		356		//memfd_create
#define		SYS_bpf		357		//bpf
#define		SYS_execveat		358		//execveat
#define		SYS_socket		359		//socket
#define		SYS_socketpair		360		//socketpair
#define		SYS_bind		361		//bind
#define		SYS_connect		362		//connect
#define		SYS_listen		363		//listen
#define		SYS_accept4		364		//accept4
#define		SYS_getsockopt		365		//getsockopt
#define		SYS_setsockopt		366		//setsockopt
#define		SYS_getsockname		367		//getsockname
#define		SYS_getpeername		368		//getpeername
#define		SYS_sendto		369		//sendto
#define		SYS_sendmsg		370		//sendmsg
#define		SYS_recvfrom		371		//recvfrom
#define		SYS_recvmsg		372		//recvmsg
#define		SYS_shutdown		373		//shutdown
#define		SYS_userfaultfd		374		//userfaultfd
#define		SYS_membarrier		375		//membarrier
#define		SYS_mlock2		376		//mlock2
#define		SYS_copy_file_range		377		//copy_file_range
#define		SYS_preadv2		378		//preadv2
#define		SYS_pwritev2		379		//pwritev2
#define		SYS_pkey_mprotect		380		//pkey_mprotect
#define		SYS_pkey_alloc		381		//pkey_alloc
#define		SYS_pkey_free		382		//pkey_free
#define		SYS_statx		383		//statx
#define		SYS_arch_prctl		384		//arch_prctl

#endif
